# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2014-2026, Lars Asplund lars.anders.asplund@gmail.com


"""
The VUnit package making Python callable from VHDL.

``vu.add_package("vunit-python-bridge", allow_setup=True)`` compiles
``python_pkg``/``python_context`` into the ``python_bridge`` library and sets up the foreign
language interface implementing them for the selected simulator:

* NVC, GHDL (VHPIDIRECT) and Questa/ModelSim (FLI) are served by the VUnit Python bridge, a
  small C library (native/*.c) embedding CPython in the simulator process.
* Riviera-PRO/Active-HDL are served by a VHPI application built with the simulator's own
  compiler driver.

Modules:

* bridge: setup of the bridge, its configuration and its generated VHDL.
* native_library: compiles and caches the library on Linux and macOS, selects the prebuilt
  DLL on Windows.
* foreign_application: builds the VHPI application.
* simulator_hooks: makes NVC and GHDL find the library.
* runtime: runs inside the simulator's embedded interpreter.

``set_relative_file_base(directory)``, called in the run script before ``add_package``, sets the
directory that ``base_path`` of ``python_pkg`` resolves relative file names against.
"""

from pathlib import Path

VHDL_PATH = Path(__file__).parent.resolve() / "hdl" / "src"

# The foreign language interface implementing the package for a simulator. VUnit says which
# simulator was selected, the package says how it is served: NVC and GHDL both go through
# VHPIDIRECT but bind the library differently, Questa/ModelSim goes through the FLI and
# Riviera-PRO/Active-HDL through a VHPI application of their own.
FOREIGN_LANGUAGE_INTERFACES = {
    "nvc": "VHPIDIRECT_NVC",
    "ghdl": "VHPIDIRECT_GHDL",
    "modelsim": "FLI",
    "rivierapro": "VHPI",
    "activehdl": "VHPI",
}

# The simulators of the table, named as a user knows them
SUPPORTED_SIMULATORS = "NVC, GHDL, Questa/ModelSim, Riviera-PRO or Active-HDL"

# The generated package giving base_path of python_pkg its directory
FILE_BASE_PACKAGE = "python_file_base_pkg"

# The directory set by set_relative_file_base, None when unset, and whether setup has run, after
# which the directory is in the generated package and can no longer be changed
_relative_file_base = None
_setup_done = False


def set_relative_file_base(directory):
    """
    Set the directory that ``base_path`` of ``python_pkg`` resolves relative file names against.

    Call it in the run script before ``vu.add_package("vunit-python-bridge", ...)``. A relative
    directory is taken from the current working directory at the time of the call.

    :param directory: An existing directory, a ``str`` or a ``Path``.
    """
    global _relative_file_base  # pylint: disable=global-statement

    if _setup_done:
        raise RuntimeError(
            'set_relative_file_base() must be called before vu.add_package("vunit-python-bridge", ...), '
            "the package has already been set up"
        )
    path = Path(directory).resolve()
    if not path.is_dir():
        raise ValueError(f"The relative file base {str(directory)!r} is not an existing directory")
    _relative_file_base = path


def _vhdl_string_literal(text):
    """
    A VHDL expression of type string for the UTF-8 bytes of a text, in ASCII: printable characters
    in a literal with its quotes doubled, other bytes as character'val(n).
    """
    parts = []
    literal = ""
    for byte in text.encode("utf-8"):
        if 0x20 <= byte <= 0x7E:
            literal += '""' if byte == ord('"') else chr(byte)
        else:
            if literal:
                parts.append(f'"{literal}"')
                literal = ""
            parts.append(f"character'val({byte})")
    if literal or not parts:
        parts.append(f'"{literal}"')
    if not parts[0].startswith('"'):
        # A string expression rather than a lone character
        parts.insert(0, '""')
    return " & ".join(parts)


def _file_base_package_text(directory):
    """
    Content of the generated python_file_base_pkg.vhd.
    """
    value = "" if directory is None else directory.as_posix()
    return f"""\
-- Generated by vunit_python_bridge.setup. Do not edit.
--
-- The directory set by vunit_python_bridge.set_relative_file_base() in the run script, empty when
-- it is not set. base_path of python_pkg resolves relative file names against it.
package {FILE_BASE_PACKAGE} is
  constant p_relative_file_base : string := {_vhdl_string_literal(value)};
end package;
"""


def _add_file_base_package(context):
    """
    Generate python_file_base_pkg and add it to the library of the package.
    """
    # pylint: disable=import-outside-toplevel
    from .bridge import _write_if_changed

    global _setup_done  # pylint: disable=global-statement

    path = Path(context.output_path) / "python_bridge" / "vhdl" / f"{FILE_BASE_PACKAGE}.vhd"
    _write_if_changed(path, _file_base_package_text(_relative_file_base))
    context.add_source_files(context.library.name, [path])
    _setup_done = True


def setup(context):
    """
    Complete the addition of the package.

    ``vunit_pkg.toml`` lists the sources both variants of the package share, this adds the
    foreign language interface of the selected simulator: the VHPI application for
    Riviera-PRO/Active-HDL, the VUnit Python bridge for everyone else.
    """
    # pylint: disable=import-outside-toplevel
    from .bridge import setup as setup_bridge
    from .foreign_application import setup_vhpi_application
    from . import simulator_hooks

    simulator_name = context.simulator_name
    if simulator_name is None:
        raise RuntimeError(
            f"The vunit-python-bridge package requires {SUPPORTED_SIMULATORS} but no simulator was found"
        )

    interface = FOREIGN_LANGUAGE_INTERFACES.get(simulator_name)
    if interface is None:
        raise RuntimeError(
            f"The vunit-python-bridge package requires {SUPPORTED_SIMULATORS}, "
            f"it has no foreign language interface for {simulator_name}"
        )

    _add_file_base_package(context)

    if interface == "VHPI":
        # Riviera-PRO/Active-HDL, the simulators served by the VHPI application
        context.add_source_files(context.library.name, [VHDL_PATH / "python_pkg_vhpi.vhd"])
        setup_vhpi_application(context.output_path, simulator_name, context.simulator_prefix)
        return

    bridge = setup_bridge(
        context.output_path,
        context.run_script_path,
        simulator_name,
        context.simulator_prefix,
        context.simulator_backend,
    )

    context.add_source_files(context.library.name, list(bridge.vhdl_files))

    simulator_hooks.register(context, bridge)
